# Generated by Django 3.2.25 on 2024-11-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241115_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliothèque',
            fields=[
                ('id_étagère', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disponibilité', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='étagères/')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id_livre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('auteur', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='livres/')),
                ('étagère', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bibliothèque')),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
    ]
