# Generated by Django 3.2.25 on 2024-11-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20241115_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id_lieu', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disponibilité', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='lieus/')),
            ],
        ),
        migrations.RemoveField(
            model_name='livre',
            name='étagère',
        ),
        migrations.DeleteModel(
            name='Bibliothèque',
        ),
        migrations.AddField(
            model_name='livre',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.lieu'),
        ),
    ]
