# Generated by Django 3.2.25 on 2024-11-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20241115_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='effet',
            field=models.CharField(choices=[('emprunté', 'Emprunté'), ('disponible', 'Disponible')], default='disponible', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lieu',
            name='disponibilité',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupé', 'Occupé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='livre',
            name='statut',
            field=models.CharField(choices=[('emprunté', 'Emprunté'), ('disponible', 'Disponible')], max_length=20),
        ),
    ]
