# Generated by Django 3.2.25 on 2024-11-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20241118_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='effet',
        ),
    ]
